name: main

on:
    workflow_dispatch:
    schedule:
        - cron: "20 16 1/3 * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: windows-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包"
              run: |
                  pip install -r ./requirements.txt
            - name: "运行 脚本"
              run: python main.py
              env:
                  PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
